<a href="https://colab.research.google.com/github/11daniel/AIPND-2022/blob/main/7th_connect_session_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas is one of darling library for Data Analysts. It comes with powerful functions and features which makes data manipulation very easy compared to traditional programming methods.
Pandas is named after "Panel-Data" and was created by Wes McKinney. It was created by keeping financial dataset by mind, but nowdays is used by every field of Data Analysis.
Pandas is a open source library and free to use and contribute to.

Pandas have fast and efficent Dataframe and Series object for data manipulation. Series deals with one dimension data and dataframe with 2 dimension dataests.

Pandas can read and write data between in memory data structure and in different format like Csv and text files, Microsoft Excel, SQL Databases, HDF5 format and much more.

Pandas can also be used with other libraries such as Matplotlib(Data Visualization Library) and is faster than other python libraries as most of the code is written in C an Cython. It have powerful group by engine which makes its aggregation faster.

## Pandas Series

Pandas Series are very similar to Numpy arrays, except that we can give them named or date time index, instead of just numeric index in Numpy array.

In [ ]:
# importing pandas and numpy library as pd and np resp(as per convention)
import pandas as pd
import numpy as np

In [ ]:
# python string list
labels = ['a', 'b', 'c', 'd']
# python number list
numbers_list = [10,20,30,40]
# numpy array
np_arr = np.array([10,20,30,45])
# python dict
dic = {'a':10, 'b':20, 'c':30, 'd':40.5}

In [ ]:
# Creating a Series from list
pd.Series(numbers_list)

0    10
1    20
2    30
3    40
dtype: int64

We can see that our list has been converted to pandas series with values and auto index assigned to them. We can provide our own index to Series.

In [ ]:
# creating series with numbers_list as data and index as labels list
ser = pd.Series(data = numbers_list, index= labels)
ser

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
ser['b']

20

We can also create pandas series from other data sources like numpy array and python dictionaries.

In [ ]:
# pandas series from numpy array
pd.Series(data = np_arr, index = labels)

a    10
b    20
c    30
d    45
dtype: int64

In [ ]:
# pandas series from dict
pd.Series(dic)

a    10.0
b    20.0
c    30.0
d    40.5
dtype: float64

Other than numeric values, you can also take create pandas series from string objects.

In [ ]:
pd.Series(data= labels)

0    a
1    b
2    c
3    d
dtype: object

Indexing with Pandas Series

In [ ]:
# create a pandas series of avengers character ratings
av_rating1 = pd.Series(data = [5,6,9,10], index = ['Thor', 'BlackWidow', 'Hulk', 'Iron Man'])
av_rating1

Thor           5
BlackWidow     6
Hulk           9
Iron Man      10
dtype: int64

In [ ]:
# another list of avengers character ratings
av_rating2 = pd.Series(data = [5,6,9,10], index = ['Hawk Eye', 'Groot', 'Rocket','Black Panther'])
av_rating2

Hawk Eye          5
Groot             6
Rocket            9
Black Panther    10
dtype: int64

In [ ]:
type(av_rating2)

pandas.core.series.Series

To access values of avengers rating we can make index call.

In [ ]:
# To get Iron Man rating
av_rating1['Iron Man']

10

In [ ]:
# Try to get rating for a charcter that is not available
av_rating1
av_rating1.get('Thanos',2)
# av_rating1['Thanos']

2

In [ ]:
# TODO: Get the ratings of Groot and Black Widow from above dataframe
av_rating2['Groot']

6

# Pandas Dataframe

Pandas Dataframe deals with two dimension data. We will directly dive in pandas Dataframe and see it in action

In [ ]:
# importing random seed
from numpy.random import randn

In [ ]:
randn(5,4)

array([[ 0.68804975, -0.9231102 , -0.81648621, -0.69559283],
       [-0.9714919 , -0.68473208,  0.14248721,  1.34412913],
       [ 0.63398507,  0.07608502, -1.41088153, -0.1341848 ],
       [ 0.88943401,  0.40135952,  0.51242076, -0.15611448],
       [ 1.32095564,  0.50851589, -1.50738705,  1.79543788]])

In [ ]:
# creating dataframe with random 5 * 4 matrix, with index and columns name provided
df = pd.DataFrame(data = randn(5,4), index = ['A', 'B', 'C', 'D', 'E'], columns= ['W','X','Y','Z'])

In [ ]:
# observing data frame values
df

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262
E -0.936927 -1.338847  0.418512  1.091853

In [ ]:
type(df)

pandas.core.frame.DataFrame

The columns W, X, Y and Z are different pandas Series and they all share common index A, B, C, D and E.
Let's grab some values from our DataFrame and confirm our learning.

In [ ]:
# getting W column from DataFrame
df['W']

A    0.250846
B   -0.417932
C   -0.760756
D    0.123231
E   -0.936927
Name: W, dtype: float64

In [ ]:
# Confirming type of our column
type(df['W'])

pandas.core.series.Series

In [ ]:
# Where as, the type of df is DataFrame
type(df)

pandas.core.frame.DataFrame

There is one more way to grab a column name but its not recommended as you can get confused with other functions and with index keys which have space between them the columns name can't be grabbed with this method.

In [ ]:
# other way to get pandas column, not recommended
df.W

A    0.250846
B   -0.417932
C   -0.760756
D    0.123231
E   -0.936927
Name: W, dtype: float64

In [ ]:
# Getting multiple columns
# You need to pass the list of columns name to get multiple columns,
# This will return the dataframe containing only X and Y columns,
# instead of series in case of single columns
df[['X', 'Y']]

          X         Y
A  1.539168 -0.335242
B -0.386019  2.085178
C  0.215520  0.276452
D -0.830121 -0.679295
E -1.338847  0.418512

In [ ]:
# confirming our claim
type(df[['X', 'Y']])

pandas.core.frame.DataFrame

We can also add new columns in our existing dataframe. Suppose you want to create a new column by adding values of X and Y columns

In [ ]:
df['X_Y_SUM'] = df['X'] + df['Y']

In [ ]:
# observing our result, a new column is been created
df

          W         X         Y         Z   X_Y_SUM
A  0.250846  1.539168 -0.335242  0.593282  1.203925
B -0.417932 -0.386019  2.085178 -0.527192  1.699160
C -0.760756  0.215520  0.276452  0.002325  0.491972
D  0.123231 -0.830121 -0.679295  1.224262 -1.509416
E -0.936927 -1.338847  0.418512  1.091853 -0.920335

To remove a column you can use drop() function. You need to pass name of the column to drop and set the axis value to 1. By default, the axis value is 0, which means it will drop value across row and to drop across columns you need to make axis = 1. There is also a boolean parameter called inplace, whose default value is False. It means that the changes will not be permanent after you drop the value, to avoid any accidental mistakes. To make permanent changes to DataFrame you need to make inplace value True.

In [ ]:
# Dropping X_Y_SUM column but inplace is False
df.drop('X_Y_SUM', axis=1, inplace=False)

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262
E -0.936927 -1.338847  0.418512  1.091853

In [ ]:
# checking the df columns, X_Y_SUM is still present
df

          W         X         Y         Z   X_Y_SUM
A  0.250846  1.539168 -0.335242  0.593282  1.203925
B -0.417932 -0.386019  2.085178 -0.527192  1.699160
C -0.760756  0.215520  0.276452  0.002325  0.491972
D  0.123231 -0.830121 -0.679295  1.224262 -1.509416
E -0.936927 -1.338847  0.418512  1.091853 -0.920335

In [ ]:
# using drop() function with inplace=True
df.drop('X_Y_SUM',axis=1, inplace=True)

KeyError: ignored

In [ ]:
# checking the df columns, X_Y_SUM is removed now
df

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262
E -0.936927 -1.338847  0.418512  1.091853

We can also use drop() to remove the row. We need to pass the row name. No need to manually change the axis value to 0 as the default value is already 0.

In [ ]:
df.drop('E')

KeyError: ignored

In [ ]:
df

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262

In [ ]:
# TODO: drop the row E with inplace kept to True
df.drop('E', inplace=True)

KeyError: ignored

In [ ]:
df

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262

**Access rows in DataFrame**
Dataframe provides two ways, **iloc** and **loc** to access the rows.
To fetch row values by index name we use **loc**. To fetch row values by index number we use **iloc**.

In [ ]:
# To get A row, use loc on df
# It returns a series as one row is selected
df.loc['A']

W    0.250846
X    1.539168
Y   -0.335242
Z    0.593282
Name: A, dtype: float64

In [ ]:
# To fetch multiple rows, you can provide list of index names
# It will return a dataframe
df.loc[['A','B']]

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192

In [ ]:
# To fetch subset of rows and columns using loc
# Fetching only A,B rows and W,X columns
df.loc[['A','B'], ['W','X']]

          W         X
A  0.250846  1.539168
B -0.417932 -0.386019

In [ ]:
# Using iloc to fetch row values by index numbers
# This will return 0th(A) row as series
df.iloc[0]

W    0.250846
X    1.539168
Y   -0.335242
Z    0.593282
Name: A, dtype: float64

In [ ]:
# To fetch subset of dataframe using iloc
# Fetching only A,B rows and W,X columns
df.iloc[0:2, 0:2]

          W         X
A  0.250846  1.539168
B -0.417932 -0.386019

In [ ]:
df

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262

In [ ]:
# TODO: select C,D rows and Y,Z columns using both loc and iloc
# df.iloc[2:, 2:]

# df.loc[['C', 'D'], ['Y', 'Z']]

**Conditional Selection in DataFrame**

In [ ]:
# Checking where df is greater than 0
# This will return a boolean dataframe where,
# values are greater than 0.
print(df)
df > 0

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262

       W      X      Y      Z
A   True   True  False   True
B  False  False   True  False
C  False   True   True   True
D   True  False  False   True

In [ ]:
# storing the value in a variable
bool_df = df > 0

In [ ]:
# Now applying to our orignal df
df[bool_df]

          W         X         Y         Z
A  0.250846  1.539168       NaN  0.593282
B       NaN       NaN  2.085178       NaN
C       NaN  0.215520  0.276452  0.002325
D  0.123231       NaN       NaN  1.224262

We can see that we get values where values are greater than 0 and NaN(null values) where the values are not greater than 0. We can complete the above condition in one step too. We generally uses these conditions with rows.

In [ ]:
# conditional statement in one step
print(df)
df[df>0]

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262

          W         X         Y         Z
A  0.250846  1.539168       NaN  0.593282
B       NaN       NaN  2.085178       NaN
C       NaN  0.215520  0.276452  0.002325
D  0.123231       NaN       NaN  1.224262

In [ ]:
# series where X column is greater than 0
df['X'] >0

A     True
B    False
C     True
D    False
Name: X, dtype: bool

In [ ]:
# getting dataframe values where column X is greater than 0
print(df)
df[df['X'] > 0]

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
C -0.760756  0.215520  0.276452  0.002325

In above text we can see that, we get only A and E rows, because the values of X columns is greter than 0 for these rows. See the output of df['X] >0 statement. Only A and E rows are positive there, so we get the datafrmae contaning rows A and E only.

In [ ]:
# TODO: Get all values from df where columns Z is less than 0
df[df['Z'] < 0]

          W         X         Y         Z
B -0.417932 -0.386019  2.085178 -0.527192

In [ ]:
# Similary we can choose selected columns too
# For the above example, we want to select only the X and Y columns
df[df['X'] >0] [['X','Y']]

          X         Y
A  1.539168 -0.335242
C  0.215520  0.276452

In [ ]:
df[df['X'] >0] [['X','Y']]

          X         Y
A  1.539168 -0.335242
C  0.215520  0.276452

In [ ]:
# If above query looks complex to you,
# First assign the result in new df object
filter_df = df[df['X'] > 0]
# then select the columns you want to choos
filter_df[['X', 'Y']]

**Multiple Condition Statements**
We have applied one condition statement till now, we can also provide multiple statment on a dataframe. Suppose you want values where X is also greater than 0 and Y is greater than 0.

In [ ]:
# Here we have surrounded out conditon in (),
# appliend &(and) operator between them
print(df)
df[(df['X']>0) & (df['Y'] >0)]

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325
D  0.123231 -0.830121 -0.679295  1.224262

          W        X         Y         Z
C -0.760756  0.21552  0.276452  0.002325

In [ ]:
# Similarly, you can perform or operation,
# using pipe(|) opeartor
df[(df['X']>0) | (df['Y'] >0)]

          W         X         Y         Z
A  0.250846  1.539168 -0.335242  0.593282
B -0.417932 -0.386019  2.085178 -0.527192
C -0.760756  0.215520  0.276452  0.002325

In [ ]:
# TODO select values where W and Z columns are greater than 0
df[(df['W'] > 0) & (df['Z']>0)]

## Missing Data

In real life dataset there is lot's of missing data. We should know how to deal with this missing data as this is very important and pandas helps us to deal with these types of datasets.

In [ ]:
# Creating a Dataframe from Dict
# np.nan is used for null or missing values
dic = {'a':[10,20,np.nan],'b':[50,np.nan,np.nan],'c':[10,20,30]}

# creating DataFrame from dict
m_df = pd.DataFrame(dic)
m_df
# Row 0 have no missing value and column c have no missing value

      a     b   c
0  10.0  50.0  10
1  20.0   NaN  20
2   NaN   NaN  30

**dropna() function**
Pandas provide dropna function which drops the na values. By default pandas will drop any row which have one or more than one missing or nan values

In [ ]:
# calling dropna on dataframe
# except 0th row all are dropped
m_df.dropna()

      a     b   c
0  10.0  50.0  10

In [ ]:
# To make these on columns we can put axis to 1
# a and b columns get dropped due to nan value
m_df.dropna(axis=1)

    c
0  10
1  20
2  30

Remember the changes that we had made are not been reflected on the actual DataFrame. To make permanent changes you need to make the value of inplace variable as True

In [ ]:
# TODO: make changes by making inplace= True
m_df

      a     b   c
0  10.0  50.0  10
1  20.0   NaN  20
2   NaN   NaN  30

**fillna() function**
fillna() function is used to fill the missing values(nan). You can customize this to fill the nan values with your needs. For example, some columns require nan to be filled with 0 while some may require it to be filled with mean value.

In [ ]:
# filling the missing value with 0
print(m_df)
m_df.fillna(value = 0)

      a     b   c
0  10.0  50.0  10
1  20.0   NaN  20
2   NaN   NaN  30

      a     b   c
0  10.0  50.0  10
1  20.0   0.0  20
2   0.0   0.0  30

**apply() function**: Suppose you want to perform a custom operation on any pandas column and have created a own function that is not present in pandas framework. Pandas can integrate your custom function and you can apply cutom function on your column using pandas **apply()** function

In [ ]:
# Creating DataFrame with a python dict
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
# a custom function which multiplies by 2
def times2(x):
    return x*2

In [ ]:
# applying times2 function on col1
applied_df =  df[['col1', 'col2']].apply(times2)

In [ ]:
df.apply(times2)

   col1  col2    col3
0     2   888  abcabc
1     4  1110  defdef
2     6  1332  ghighi
3     8   888  xyzxyz

In [ ]:
# TODO: Create a funtion add_10 which add value by 10,
# and apply it on col1 of above dataframe

In [ ]:
d

# Reading Files using Pandas

Pandas have API to read CSV, SQL, MS Excel, json, txt and many other file formats from local computer or from  internet URL. Everything that we have learnt till now is by creating our own DatFrame. In real world scenario we will be provided by the data files with different file formats. !

In [ ]:
# Reading the csv file california_housing_test.csv using read_csv funtion
# You need to provide the file path or URL path here
# The data will be read as pandas DataFrame
# This file is present in our colabs environment
df = pd.read_csv('./sample_data/california_housing_test.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

 Exercise
 1. Calculate the actual house value by formula **(2*total_rooms) + (0.25 * population) + (0.30 * housing_median_age)**
 2. Search with houses with **housing_median_age less than 25** and **total_bedrooms greater than 300**
 3. Cacluate the average total_room for california

In [ ]:
def test_function():
  pass